### ISSUE TITLE
Provide markers with the functionality to see their past markings

### ISSUE THREAD

**Issue by naagma5** [Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension#13]
**Is your feature request related to a problem? Please describe.**
Currently, the markers cannot see content that they have marked as potentially racially biased. 

**Describe the solution you'd like**
Provide a way for markers to see the content that they have marked as racially biased so that they can update or change what they have marked.

**Comment by josiemundi** [comment]
Hey @naagma5 

Currently in the tool, the user can see content that they have already marked (these show still higlighted with the corresponding category color) and they can update and delete it. Perhaps you can be more specific about the functionality that you would like to see added.

Thanks!

**Comment by josiemundi** [comment]
Closing because the tool already does this and we don't have any more specific info about the issue.
