### ISSUE TITLE
Multi-browser capability

### ISSUE THREAD

**Issue by iainmccombe** [Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension#14]
Currently the marker only works as a Chrome browser extension. It would be better to have a version that works for each of the mainstream browsers (Safari and Firefox) so that more people are able to use it easily.

**Comment by josiemundi** [comment]
@iainmccombe Apple allow you (for example) to port chrome extensions to Safari. You can also port them to Firefox. For Apple there is a yearly charge. However, this is something we could look at when we think we are in a place to have the tool available in other browsers. 

It would be good if we could prioritise which browsers we want this to be available for.

**Comment by josiemundi** [comment]
@naagma5 @upkarlidder I am closing this as it is very broad. It's easy to port browser extensions once we know which ones we want. I can't see this being needed for a little while so I think we can raise another issue when that time comes.
