### ISSUE TITLE
Add github actions for accessibility testing

### ISSUE THREAD

**Issue by AndrewJamison** [Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension#39]
**Is your feature request related to a problem? Please describe.**
There is currently no automated accessibility tests. We want to lighten the manual workload for running accessibility tests. 

**Describe the solution you'd like**
Adding github actions to automate the accessibility tests that will be added in a seperate issue

**Describe alternatives you've considered**
N/A

**Additional context**
Accessibility tests will be added here https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension/issues/37

**Comment by kayleekimberly** [comment]
@upkarlidder @demilolu This issue needs the ms-cohort-claimed label

**Comment by kayleekimberly** [comment]
This is duplicated by [this issue](https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension/issues/37)
